## COASTAL BUFFERS DERIVED FROM Global Shoreline Dataset ##
# https://gee-community-catalog.org/projects/shoreline/
# THIS SCRIPT USES SHORELINE DERIVED FROM REMOTE SENSE TO GENERATE THE 
# COASTAL BUFFERS IMPROVING.

# ## Luis de la Rua - luisr@spc.int - January 2025 ##
## Statistics for Development Division - SDD ##

# 1. SETTINGS =================================================================
source("setup.R")

# Set data paths
layers <- ("C:/Users/luisr/SPC/SDD GIS - Documents/Coastal Population/CoastPop_Update2025/Data/")
output <- ("C:/Users/luisr/SPC/SDD GIS - Documents/Coastal Population/CoastPop_Update2025/results/")

# List of countries in pacific region
iso3_list <-c ("ASM","COK","FSM","GUM","MHL","MNP","NCL","NIU","NRU","PLW","PNG","PYF","SLB","TON","TUV","VUT","WLF","WSM") # countries not touched by dateline
iso3_dline_countries <- c("FJI","KIR")

# 2. LIST ALL DATASETS DOWNLOADED FROM GEE ----
gs_list <- list.files(paste0(layers,"coastal buffers globalshore/input/"), pattern = ".shp", full.names = TRUE)
gs_list

# 3. PROCESS ALL THE SHORELINE LAYERS
# tic()
# for(file in gs_list){
#   # Load shoreline polygon
#   poly <- vect(file)
#   # get iso code for later
#   iso3 <- substr(basename(file), 1, 3)
#   
#   # create iso3 attribute table from the 3 first characters of the filename
#   poly <- poly %>% 
#     mutate(iso3 = iso3) %>% 
#     select(iso3) %>% 
#     group_by(iso3) %>% 
#     summarise()
#   
#   # convert into line
#   line <- as.lines(poly)
#   # Create buffers 1, 5 and 10km 
#   b1 <- buffer(line, 1000) %>% 
#     mutate(buffer = "1km")
#   b5 <- buffer(line, 5000) %>% 
#     mutate(buffer = "5km")
#   b10 <- buffer(line, 10000) %>% 
#     mutate(buffer = "10km")
#   # Export buffers
#   writeVector(b1, paste0(layers,"coastal buffers globalshore/",iso3,"_1km.gpkg"), overwrite = T)
#   writeVector(b5, paste0(layers,"coastal buffers globalshore/",iso3,"_5km.gpkg"), overwrite = T)
#   writeVector(b10, paste0(layers,"coastal buffers globalshore/",iso3,"_10km.gpkg"), overwrite = T)
#   # Checks
#   print(paste0(b1$iso3,'-' ,nrow(b1),'-' , crs(b1),'-' , names(b1)))
#   print(paste0(b5$iso3,'-' ,nrow(b5), '-' ,crs(b5),'-' , names(b5)))
#   print(paste0(b10$iso3,'-' ,nrow(b10), '-' ,crs(b10), '-' ,names(b10)))
# 
# }
# toc()

# Start timing
tic("Processing all shoreline layers")

for (file in gs_list) {
  cat("\nProcessing file:", file, "\n")
  
  # Load shoreline polygon
  poly <- vect(file)
  iso3 <- substr(basename(file), 1, 3) # Extract ISO3 code
  epsg_code <- crs(poly, proj = TRUE) %>% 
    sub(".*EPSG:(\\d+).*", "\\1", .) # Extract EPSG code
  
  cat("Loaded file for ISO3:", iso3, "with EPSG code:", epsg_code, "\n")
  
  # Create ISO3 attribute and dissolve polygons by ISO3
  cat("Processing polygons to dissolve by ISO3...\n")
  poly <- poly %>%
    mutate(iso3 = iso3) %>%
    select(iso3) %>%
    group_by(iso3) %>%
    summarise()
  
  # Convert polygons to lines
  cat("Converting polygons to lines...\n")
  line <- as.lines(poly)
  
  # Create buffers at 1, 5, and 10 km
  cat("Creating buffers of 1km, 5km, and 10km...\n")
  b1 <- buffer(line, 1000) %>%
    mutate(buffer = "1km")
  b5 <- buffer(line, 5000) %>%
    mutate(buffer = "5km")
  b10 <- buffer(line, 10000) %>%
    mutate(buffer = "10km")
  
  # Define output paths
  output_dir <- paste0(layers, "coastal buffers globalshore/")
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    cat("Created output directory:", output_dir, "\n")
  }
  
  # Export buffers
  cat("Exporting buffers for ISO3:", iso3, "...\n")
  writeVector(b1, paste0(output_dir, iso3, "_1km.gpkg"), overwrite = TRUE)
  writeVector(b5, paste0(output_dir, iso3, "_5km.gpkg"), overwrite = TRUE)
  writeVector(b10, paste0(output_dir, iso3, "_10km.gpkg"), overwrite = TRUE)
  
  # Perform and print checks
  cat("Export successful. Performing checks...\n")
  print(paste0("1km Buffer: ", iso3, " - Features: ", nrow(b1), " - EPSG: ", epsg_code, " - Attributes: ", paste(names(b1), collapse = ", ")))
  print(paste0("5km Buffer: ", iso3, " - Features: ", nrow(b5), " - EPSG: ", epsg_code, " - Attributes: ", paste(names(b5), collapse = ", ")))
  print(paste0("10km Buffer: ", iso3, " - Features: ", nrow(b10), " - EPSG: ", epsg_code, " - Attributes: ", paste(names(b10), collapse = ", ")))
}

# End timing
toc()

# There is manual processing done after this process
# Remove rivers and country borders from PNG
# Fill rings from 5 and 10 Nauru buffers probably generated by a topology error


